import React from "react";
import Formulario from "../../components/client/vende/formulario";
import Head from "next/head";

const VendeAuto = () => {
  return (
    <>
      <Head>
        <title>Multicars | Vende tu auto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vector.png" />
      </Head>
      <div className="pt-[75px] bg-white">
        <div className="flex flex-col justify-start relative w-full items-center">
          <div className="bg-black relative w-full h-5" />
          <div className="md:bg-[url(/media/portadaNosotros.png)] bg-[url(/media/PortadaVende.png)] bg-cover bg-50%_50% bg-blend-normal flex flex-col justify-start relative w-full h-[600px] shrink-0 items-start">
            <div className="bg-[url(https://file.rendit.io/n/pXRiIiuAUbsoLUueb6CT.svg)] bg-cover bg-50%_50% bg-blend-normal flex flex-col justify-start relative h-32 shrink-0 items-start pt-6 pb-8 pl-16">
              <h1 className="whitespace-nowrap text-3xl  font-bold uppercase text-white mr-[145px] relative">
                Vendé tu usado <br />
                en Multicars.
              </h1>
            </div>
          </div>
        </div>
        <div className="p-5 md:p-12 space-y-8 md:space-y-0 flex flex-col justify-center md:flex-row md:gap-12">
          <iframe
            src="https://www.youtube.com/embed/wNV4C4heTNE"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
            className="w-full h-[200px] md:h-[400px] rounded-3xl md:w-1/2"
          ></iframe>
        </div>

        <div className="relative flex flex-col justify-start w-full items-center pt-10 pb-[414px] px-[560px] my-20">
          <img
            src="https://file.rendit.io/n/VZJqvXFXEwmgHdsywDhX.svg"
            className="w-[1150px] h-[5.2rem] min-h-0 min-w-0 absolute top-0 left-0"
          />
          <h1 className="whitespace-nowrap text-4xl  font-bold leading-[10px] text-white relative">
            COTIZÁ TU AUTO
          </h1>
          <div className="rounded-br-[26px] w-full h-[419px] bg-black absolute top-20 left-0 flex flex-col justify-start  items-center pt-12 pb-10 ">
            <span className="text-primary font-bold text-sm md:text-base flex justify-center mb-4 ">
              Para comenzar contanos cuál es tu auto
            </span>

            <Formulario padding={"md:px-0 px-5"} />
          </div>
        </div>
      </div>
    </>
  );
};

export default VendeAuto;
