import Head from "next/head";
import HomeComponent from "../components/client/Home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Multicars </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vector.png" />
      </Head>
      <HomeComponent></HomeComponent>
    </div>
  );
}
